server:
  port: 8081
  servlet:
    context-path: /article  # 微服务统一路径

spring:
  application:
    name: article
  datasource:
    url: jdbc:mysql://localhost:3306/aphrora_letters?useUnicode=true&characterEncoding=utf8&allowMultiQueries=true&serverTimezone=UTC
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver

mybatis-plus:
  global-config:
    db-config:
      logic-delete-field: is_effective
      logic-delete-value: 0
      logic-not-delete-value: 1

logging:
  level:
    team.aphroraletters.article: info
  pattern:
    dateformat: MM-dd HH:mm:ss:SSS
  file:
    path: /logs

sa-token:
  # token名称 (同时也是cookie名称)
  token-name: satoken-al
  # token有效期，单位s 默认30天, -1代表永不过期
  timeout: 2592000
  # token临时有效期 (指定时间内无操作就视为token过期) 单位: 秒
  activity-timeout: -1
  # 是否允许同一账号并发登录 (为true时允许一起登录, 为false时新登录挤掉旧登录)
  is-concurrent: true
  # 在多人登录同一账号时，是否共用一个token (为true时所有登录共用一个token, 为false时每次登录新建一个token)
  is-share: true
  # token风格
  token-style: uuid
  # 是否输出操作日志
  is-log: false

management:
  endpoints:
    web:
      exposure:
        include: "*"
